// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE2PeuEEHPwNE31Dfo-E59bAc0jXeLtbI',
    appId: '1:583660307478:web:b492f51a8fe3cf0092a137',
    messagingSenderId: '583660307478',
    projectId: 'flutter-gen-iu--demo',
    authDomain: 'flutter-gen-iu--demo.firebaseapp.com',
    storageBucket: 'flutter-gen-iu--demo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhnVoYZCeex0mWEvi0AMJWqQ3C7R7R3MU',
    appId: '1:583660307478:android:5c2765322a16a96292a137',
    messagingSenderId: '583660307478',
    projectId: 'flutter-gen-iu--demo',
    storageBucket: 'flutter-gen-iu--demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAuhZitheMA0ZYnvgglw0gnj8lgZ7HF2c',
    appId: '1:583660307478:ios:4b182125c7ccb57192a137',
    messagingSenderId: '583660307478',
    projectId: 'flutter-gen-iu--demo',
    storageBucket: 'flutter-gen-iu--demo.firebasestorage.app',
    iosBundleId: 'com.example.flutterGenuiDemo',
  );
}
